source 'http://rubygems.org'

gem 'mysql', '2.9.1'
gem 'rails', '2.3.5'
gem 'i18n','0.4.2'
gem 'rush'
gem 'declarative_authorization','0.5.1'
gem 'rb-readline'
gem 'nokogiri','1.5.10'
gem 'multi_json', '~> 1.0'
gem 'fastercsv'
gem 'oauth2'
gem 'faraday'
gem 'addressable'
